# Generated by Django 4.0.4 on 2022-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_user_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bookings',
            name='booked_time',
            field=models.CharField(max_length=6),
        ),
    ]
