# Generated by Django 4.0.4 on 2022-06-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_user_bookings_booked_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletable',
            options={'ordering': ['-booking_date']},
        ),
    ]
