# Generated by Django 4.0.4 on 2022-06-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_availabletable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletable',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterField(
            model_name='user_bookings',
            name='booked_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.availabletable'),
        ),
    ]
