# Generated by Django 4.0.4 on 2022-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_availabletable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bookings',
            name='booked_date',
            field=models.DateField(),
        ),
    ]
